<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>Terms and Conditions</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">

    <!-- External CSS libraries -->
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="css/animate.min.css">
    <link rel="stylesheet" type="text/css" href="css/bootstrap-submenu.css">

    <link rel="stylesheet" type="text/css" href="css/bootstrap-select.min.css">
    <link rel="stylesheet" type="text/css" href="css/magnific-popup.css">
    <link rel="stylesheet" type="text/css" href="css/daterangepicker.css">
    <link rel="stylesheet" href="css/leaflet.css" type="text/css">
    <link rel="stylesheet" href="css/map.css" type="text/css">
    <link rel="stylesheet" type="text/css" href="fonts/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" type="text/css" href="fonts/linearicons/style.css">
    <link rel="stylesheet" type="text/css"  href="css/jquery.mCustomScrollbar.css">
    <link rel="stylesheet" type="text/css"  href="css/dropzone.css">
    <link rel="stylesheet" type="text/css"  href="css/slick.css">

    <!-- Custom stylesheet -->
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link rel="stylesheet" type="text/css" id="style_sheet" href="css/skins/default.css">

    <!-- Favicon icon -->
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" >
    
    <!-- Google fonts -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,300,700">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800%7CPlayfair+Display:400,700%7CRoboto:100,300,400,400i,500,700">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link rel="stylesheet" type="text/css" href="css/ie10-viewport-bug-workaround.css">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script  src="js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script  src="js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script  src="js/html5shiv.min.js"></script>
    <script  src="js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="page_loader"></div>

<!-- Main header start -->
 <?php include("header.php");?>
<!-- Main header end -->

<!-- Sub banner start -->
<div class="sub-banner overview-bgi">
    <div class="container">
        <div class="breadcrumb-area">
            <h1>Terms and Conditions</h1>
            <ul class="breadcrumbs">
                <li><a href="index.php">Home</a></li>
                <li class="active">Terms and Conditions</li>
            </ul>
        </div>
    </div>
</div>
<!-- Sub Banner end -->

<!-- About city estate start -->
<div class="about-real-estate  content-area-5">
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-6 col-md-12 col-sm-12 col-xs-12">
                
				  <div class="WordSection1">
    <p class="MsoNormal" style='margin-top:0in;margin-right:0in;margin-bottom:.5pt; margin-left:0in;text-indent:0in;line-height:107%'><span style='font-size:28pt; line-height:107%'>Terms of Service</span></p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.35pt; margin-left:-.25pt'>We offer you the websites, applications, services and content on BeLocalFocused.com and its affiliated sites and services (“BeLocalFocused”) on the condition that you agree to the following terms.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.4pt; margin-left:-.25pt'>EACH TIME YOU ACCESS, USE OR REGISTER FOR BELOCAFOCUSED.COM, YOU ARE SIGNIFYING YOUR AGREEMENT TO THE FOLLOWING TERMS AND CONDITIONS (either the “Terms of Service” or “Agreement”).</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.7pt; margin-left:-.25pt'>You may not use BeLocalFocused if you do not agree to these Terms of Service</p>
    <h3 style='margin-left:-.25pt'>Here is a Summary of Our Terms</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> BeLocalFocused.com is provided by BeLocalFocused, its licensors and affiliates (either “we” or “us”).</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> These Terms of Service consist of the terms below, our privacy policy, and any supplemental terms that our vendors, Contributors or we may apply to a specific feature, product or subscription that you may purchase from us.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> We can change these terms at any time, in which such changes take effect after we post notices of the changes.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> We may change or discontinue any feature on BeLocalFocused at any time.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You agree to pay us for any purchases and subscriptions ordered by you.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> We give you a limited right to access and use BeLocalFocused. You are not authorized to access BeLocalFocused or its servers and databases to scrape or “data mine” data in our servers.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You may not resell or redistribute BeLocalFocused services and databases unless otherwise authorized by us in writing.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You must comply with these terms and all applicable laws when you use BeLocalFocused.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> These Terms of Service have the same legal effect as an agreement in writing.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You will own the Content (defined below) you post on BeLocalFocused. You give us the right to use and re-purpose the Content that you post on BeLocalFocused. We own all compilation rights in our site and services.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You own or have the right to submit any Content you post on BeLocalFocused.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> We offer BeLocalFocused “AS IS” and without warranties of any kind, and we limit our liability to you.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:9.7pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> BeLocalFocused, at its sole discretion, reserves the right to suspend or terminate your account and refuse any and all current or future use of the Service for any reason at any time. Such termination of the Service will result in the deactivation or deletion of your account or your access to your account, and immediate archival or deletion of all data in your account. BeLocalFocused reserves the right to refuse service to anyone in its sole and absolute discretion.</p>
    <p class="MsoNormal" style='margin:0in;text-indent:0in;line-height:107%'><span style='font-size:18.0pt;line-height:107%'>&nbsp;</span></p>
    <h3 style='margin-left:-.25pt'>About These Terms</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.1pt; margin-left:-.25pt'>In this Agreement, (a) the term “you” means the person who (or the entity on behalf of whom you are acting) that is agreeing to these Terms of Service; (b) the term “Content” means any data, information, text, images, audio, video, profiles and all other forms of data and communications on BeLocalFocused that is provided by us, our Contributors, affiliates and users; and (c) the term “Contributors” means our users, third-party providers, licensors and businesses, Agencies (defined below), Clients (defined below) and proprietors that post Content, which include any profiles and listings, on BeLocalFocused. These Terms of Service serve as a binding contract between you and us and govern your relationship with us.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.9pt; margin-left:-.25pt'>Additional terms may apply to certain subscriptions, purchases, products, services and Content offered by BeLocalFocused or a Contributor.&nbsp;</p>
    <h3 style='margin-left:-.25pt'>Changes to These Terms</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.85pt; margin-left:-.25pt'>We may make changes to the terms of this Agreement at any time. All modifications will be posted on BeLocalFocused properties and such modifications take effect after we post them. You assume the responsibility to review this Agreement on a regular basis to keep yourself informed of any modifications. If you disagree with any material changes to this Agreement, you must discontinue your use of BeLocalFocused. Your ongoing use of BeLocalFocused after the changes take effect signifies your agreement to the new terms.</p>
    <h3 style='margin-left:-.25pt'>About BeLocalFocused and its Services</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.9pt; margin-left:-.25pt'>BeLocalFocused offers website, business profile databases, related services, and other consulting services to help businesses grow, which collective we refer to as “BeLocalFocused” in this Agreement. We may change, update or discontinue any offering, feature or Content on BeLocalFocused at any time and without notice and without liability to you.</p>
    <h3 style='margin-left:-.25pt'>Registration and Eligibility</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.35pt; margin-left:-.25pt'>Registration is optional; however, you will need to register with us to use all of our features and services. We will open an individual membership profile account when you register on BeLocalFocused. If you open a membership account, we will give you the ability to set up a profile for your business and use other features of BeLocalFocused.&nbsp; In order to register with BeLocalFocused, you must meet the following qualifications:</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You must be at least 18 years of age and have the legal capacity to agree to these Terms of Service.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:3.25pt; margin-left:36.05pt;text-indent:-18.05pt;line-height:107%'><span style='font-size:10.0pt;line-height:107%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You must provide true, accurate, current and complete registration information.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You agree to keep this information up-to-date.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You must abide at all times with the Terms of this Agreement.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> If you are registering on behalf of a business or entity, you must have authority to act on behalf of such business or entity.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.9pt; margin-left:-.25pt'>We are not responsible if we are unable to communicate with you because you have not kept your registration information up to date. By accessing and/or registering for the use of BeLocalFocused, you represent and warrant that (a) you have the authority and legal capacity to enter into the Agreement and follow its obligations, (b) you have the authority to bind your principal or employer company if you are applying on behalf of a business, and (c) you are providing true, complete and current information.</p>
    <h3 style='margin-left:-.25pt'>Your Information</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:0in; margin-left:-.25pt'>When you submit information about you to us, you agree that we may collect and use your information as disclosed in our Privacy Policy. If you are accessing BeLocalFocused from within the State of California, you acknowledge that BeLocalFocused collects personal information as defined in the California Consumer Protection Act of 2018.&nbsp;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:0in;margin-bottom:4.4pt; margin-left:0in;text-indent:0in;line-height:107%'>&nbsp;</p>
    <h3 style='margin-left:-.25pt'>Ownership</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.85pt; margin-left:-.25pt'>Our Contributors, licensors and we own all rights in the BeLocalFocused site, Content, aggregate user review ratings, data, text, designs, pages, print screens, the organization and structure of our data and Web sites, trademarks, logos, trade names, images, artwork, photographs, audio and video clips, and HTML code, source code, or software that resides or is viewable or otherwise discoverable on BeLocalFocused. We (or as applicable, our licensors) own all intellectual property rights in our databases’ code, indexes, algorithms, organization and structure, and compilation of data. Except for the limited license we grant to you below, you obtain no other rights in BeLocalFocused or its Content.</p>
    <h3 style='margin-left:-.25pt'>License and Authorized Uses</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.85pt; margin-left:-.25pt'>The BeLocalFocused services and its Content are licensed, not sold. We grant you a nonexclusive, non-transferable, limited license to access and use BeLocalFocused and the Content subject to the terms and limitations of this Agreement. Any use beyond this limited license is prohibited. You may create a profile only on your own behalf or on behalf of your business. Unless otherwise provided in any supplemental terms, you may download and temporarily store Content that you purchase to one computing device under your exclusive control. You may use such Content only (1) to display internally such Content for your internal business and research needs and (2) to quote and excerpt from such Content. You may also create one printout of such Content for your internal use and you may not further distribute the printouts. We do not authorize any other access and use of BeLocalFocused not expressly provided in this Agreement.</p>
    <h3 style='margin-left:-.25pt'>Unauthorized Access and Use of BeLocalFocused</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:-.25pt'>You may not directly, indirectly or through any intermediary:</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Copy, scrape, crawl, mine, spider, record, aggregate, resell, retransmit, redistribute, modify, translate or otherwise create derivative works of BeLocalFocused, its databases, Content, or its user IDs or passwords;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Export or re-export BeLocalFocused services or its technology and applications in violation of any United States export law or regulation;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Violate these Terms of Service;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Violate the intellectual property rights, privacy rights or the rights of others;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Frame our Web sites, pages or other Content;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Use any automated means to create one or more profiles or user IDs;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Offer services or assist any other party to circumvent the restrictions in these Terms of Service;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Store or use our databases or Content to create an archival, searchable database of Content or compile data in a way that can be used by a competitive listing product or service;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.7pt; margin-left:36.05pt;text-indent:-18.05pt;line-height:99%'><span style='font-size:10.0pt;line-height:99%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Use our data, information about our customers or Content to send spam, unsolicited communications or other mass communications to consumers or third parties;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Use our trademarks, logos, or trade names without our express authorization to solicit your own customers, to imply any affiliation between you and us, or to make misrepresentations about BeLocalFocused or us;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Make excessive traffic demands on our computer networks, impair, damage, disable or otherwise attack BeLocalFocused or our computer networks, or attempt to gain unauthorized access to BeLocalFocused through any manual or automated means;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Modify, adapt, sub-license, translate, sell, reverse engineer, decompile or disassemble any portion or BeLocalFocused or otherwise attempt to derive any source code or underlying ideas or algorithms of BeLocalFocused;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Remove any copyright, trademark or other proprietary rights notices;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Impersonate any person, business or entity, including our company and our employees and agents;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Create profiles of a third party without the express authorization from such person or entity.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:0in;margin-bottom:8.95pt; margin-left:36.05pt;text-indent:0in;line-height:107%'>&nbsp;</p>
    <h3 style='margin-left:-.25pt'>Your Responsibilities</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.55pt; margin-left:-.25pt'>You are responsible for all activities under your membership account, including all legal liability incurred from the use of your profile by you or others. You may not give access to your profile, or disclose your password to others. You may not harvest Content for the purposes of sending spam or other forms of unsolicited communications. You are responsible for keeping your profile information, including all passwords, confidential. You shall be solely responsible and accept all liability for your (including your agents’ and representatives’) changes, edits, modifications or additions to the information and/or data you receive through BeLocalFocused. We are not responsible if your profile or account is compromised if any of your devices containing your profile (such as a mobile device) is lost or stolen. You are responsible for notifying us immediately if your profile has been compromised.</p>
    <h3 style='margin-left:-.25pt'>Use of Content, Forums, Comment Areas and Message Boards</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.35pt; margin-left:-.25pt'>BELOCALFOCUSED PROVIDES THE CONTENT “AS IS” AND YOUR USE OR RELIANCE ON SUCH MATERIALS ARE SOLELY ARE YOUR OWN RISK. We offer the Content for general information, general discussion, and education purposes only. This Content may be provided by us, our Contributors and members. Do not construe any Content on BeLocalFocused is endorsed or verified by our Contributors or us. BeLocalFocused is not intended to provide personalized investment or other regulated professional advice. Nothing contained on BeLocalFocused should be construed as providing (a) a solicitation, recommendation, endorsement, or offer to buy or sell any securities or other financial instruments or (b) a recommendation to any specific individual or business that any particular security, portfolio of securities, transaction or investment strategy is suitable for you or any specific person. Our contributors and we are not liable to you or any third party for the truthfulness, accuracy, reliability, completeness, timeliness, legality or applicability of any Content posted or otherwise transmitted by any users. We do not endorse the opinions expressed by any users. We reserve the right, but we shall have no obligation or responsibility to you or any third party, to pre-screen, review, flag, filter, modify, refuse or remove any or all Content on BeLocalFocused that violates this Agreement, as we determine in our sole discretion.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.65pt; margin-left:-.25pt'>You acknowledge that we may, but we have no obligation to you or any third party, to investigate and take appropriate technical, legal and equitable action against anyone who, in our sole discretion, violates this Agreement, including but not limited to, terminating their membership account and/or reporting such Content, conduct, or activity to law enforcement authorities. We may access, preserve or disclose information you provide, including user Content, when we have a good faith belief that such access, preservation or disclosure is necessary in order to: (i) protect or defend our and our Contributors legal rights or property, or their employees, agents and contractors (including enforcement of our agreements); (ii) protect the safety and security of users of BeLocalFocused or members of the public including acting in urgent circumstances; (iii) protect against fraud or for risk management purposes; or (iv) comply with application laws or other legal process.</p>
    <h3 style='margin-left:-.25pt'>Important Terms About the Content You Post on BeLocalFocused</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.15pt; margin-left:-.25pt'>BeLocalFocused offers features where Contributors may post Content such as business profiles, ratings and comments on forums. You remain the owner of any Content you post on BeLocalFocused.&nbsp; However, by submitting Content to BeLocalFocused:</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You grant us, our affiliates, and distributors a perpetual, worldwide and royaltyfree right to use, copy, store, display, perform, distribute, redistribute, syndicate, transmit, adapt and promote your Content, and any information contained</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.55pt'>within such Content, in any medium including, without limitation, the use of your user name and alias associated with your Content;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You grant other users of BeLocalFocused free permission to view and use your Content; and</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> We own all rights in any compilation and collective works of Content as organized and presented on BeLocalFocused and retained in our databases.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:0in; margin-left:-.25pt'>If you participate in any feature on BeLocalFocused that allows users to share, modify, or combine user Content with other Content, you grant us and our users an irrevocable, royalty-free, fully paid up, perpetual, worldwide right and license to use, share, reproduce, modify, create derivative works, display, distribute and perform your Content on BeLocalFocused. Any suggestions or ideas that you submit to us become our property and can be used by us for any purpose. We will not pay you for your submissions. We may refuse to publish, and may remove the Content from</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.1pt; margin-left:-.25pt'>BeLocalFocused at any time and for any reason. You represent and warrant to us that you have all rights necessary for you to grant the permissions in this section.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.35pt; margin-left:-.25pt'>In addition to the restrictions specified above, you may not use BeLocalFocused to submit Content or engage in any conduct that:</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Violates laws pertaining to securities and investment advising, including any rules and regulations of the U.S. Securities and Exchange Commission and the national or other securities exchanges, especially and including the rule against making false or misleading statements to manipulate the price of any security;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Posts or transmits any advertising, promotional materials, or other forms of solicitation including chain letters and pyramid schemes;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Violates or infringes the rights of others, including, without limitation, patent, trademark, trade secret, copyright, publicity, privacy, or other proprietary rights;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.7pt; margin-left:36.05pt;text-indent:-18.05pt;line-height:99%'><span style='font-size:10.0pt;line-height:99%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Discloses anyone’s identification documents (such as driver’s license numbers, social security numbers_, financial information, or other private or sensitive information;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Is unlawful, threatening, abusive, harassing, invasive of another’s privacy, tortious, or contains explicit or graphic descriptions, or accounts of, sexual acts;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Publishes falsehoods or misrepresentations that could damage any person or entity, or is otherwise defamatory, libelous or deceptive;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Victimizes, harasses, degrades, or intimidates an individual or group of individuals on the basis of religion, gender, sexual orientation, race, ethnicity, age, or disability;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Impersonates any person, business or entity, including without limitation, impersonating others to post favorable comments to your profile or business;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Contains viruses or any other computer code, files or programs that interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment, or otherwise permit the unauthorized use of a computer or computer network;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Violates any applicable local, state, federal, national or international law, statute, ordinance, or regulation including, without limitation, Credit Card Association</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.55pt'>rules, consumer protection laws, election laws, laws regulating tobacco-related products and electronic cigarette sales, and laws pertaining to unfair competition, false advertising and discrimination;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Promotes dating, escort, strip-tease acts or prostitution;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Is associated with the sale of (a) any controlled drug that requires a prescription from a licensed practitioner unless you are authorized by the National Association of Boards of Pharmacy to offer such products as a Verified Internet Pharmacy Practice Site and only if such a prescription has been issued by the practitioner after a bona fide examination of the patient; or (b) any over-thecounter drug, unless the sale of such product, without a prescription, has been approved by the Food &amp; Drug Administration; or (c) nonprescription drugs that make false or misleading treatment claims or treatment claims that require FDA approval; or (d) any drug or controlled substance that BeLocalFocused believes to be or may become harmful, unlawful, or prohibited;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Violate Title IV of the Higher Education Act of 1965, Family Education Rights and</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:36.55pt'>Privacy Act, Truth in Lending Act, Real Estate Settlement Procedures Act, Equal</p>
    <p class="MsoNormal" align="center" style='margin-top:0in;margin-right:4.9pt; margin-bottom:3.45pt;margin-left:0in;text-align:center;text-indent:0in; line-height:107%'>Credit Opportunity Act, Fair Housing Act or the Fair Credit Reporting Act;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Is associated with the sale of firearms;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Involves posting “fake” endorsements or recommendations; or</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:0in;margin-bottom:11.6pt; margin-left:0in;text-indent:0in;line-height:107%'>&nbsp;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.9pt; margin-left:-.25pt'>You acknowledge that posting Content that violate the terms of this Agreement, the rights of others, or any applicable law or regulation, may result in civil or criminal liability. You represent and warrant to us that your conduct on BeLocalFocused will at all times comply with the terms of this Agreement.</p>
    <h3 style='margin-left:-.25pt'>Data Backup</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:18.35pt; margin-left:0in;text-align:justify;text-justify:inter-ideograph;text-indent: 0in;line-height:99%'>You are solely responsible for backing up any Content that you store on any customizable area on BeLocalFocused. We are not responsible for the loss of any data or Content you elect to store on BeLocalFocused.</p>
    <h3 style='margin-left:-.25pt'>Your Representations</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:-.25pt'>By submitting Content on BeLocalFocused, (a) you represent and warrant that your Content is true, accurate, current, complete and that you own or have express permission to post the materials on BeLocalFocused; (b) that you have the authority to post such Content and that such submission will not violate any trade secrets, confidential information, or violate any securities laws; (c) in the event your Content contains the name, image, video, audio or participation by individuals, performers or entities other than you, that you have obtained such parties consent to their appearance or use of their contribution in the Content that you upload; and (d) you agree to indemnify and hold us harmless from all claims, costs and expenses (including legal expenses) arising out of any Content posted or published by you that are in breach of this section.</p>
    <h3 style='margin-left:-.25pt'>Fees and Payment – Optional Services and Content</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.35pt; margin-left:-.25pt'>You agree to pay the applicable fees and charges for membership plans and other purchases that you make from us. We may limit the number of promotions for which you may be eligible in a given period. Your payment and renewal terms at the time you make a purchase from BeLocalFocused are disclosed in these Terms of Service or in the shopping cart; you can also review your payment terms from time to time by visiting the “My Account” area on BeLocalFocused.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:0in; margin-left:-.25pt'>You must give us accurate billing and payment information and keep this information up-to-date. Every time you make a purchase or obtain a service from BeLocalFocused, you reaffirm that (i) we are authorized to charge your designated payment method; (ii) we may submit charges incurred under your profile for payment; and (iii) you will be responsible for such charges. YOU AGREE THAT WE MAY CHARGE YOUR PAYMENT METHOD FOR ALL AMOUNTS DUE TO US WITHOUT ADDITIONAL NOTICE OR</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.35pt; margin-left:-.25pt'>CONSENT unless required otherwise by law. If we do not receive payment from your designated payment method, you agree to pay all amounts due upon demand by us. You are responsible for all charges incurred under your profile made by you or anyone who uses your account associated with your profile. We may, in our discretion, post charges to your payment method individually or may aggregate your charges with other purchases you make on BeLocalFocused. You agree that any submissions you make for electronic purchases constitute your intent and agreement to be bound by the terms of and pay for such purchases.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:11.9pt; margin-left:-.25pt'>BeLocalFocused may change, add or delete any aspect of the Service at any time.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.35pt; margin-left:-.25pt'>Subscription services will remain available during the subscription period and will not be available after the subscription period ends. In instances wherein an immediate deactivation or refund occurs, the availability of services and content may be terminated immediately.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>EACH PARTY ON BEHALF OF ITSELF AND ITS AFFILIATES DISCLAIMS ALL IMPLIED</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>WARRANTIES, INCLUDING WITHOUT LIMITATION for SATISFACTORY QUALITY,</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>MERCHANTABILITY AND FITNESS FOR ANY PURPOSE. TO THE FULLEST EXTENT</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.1pt; margin-left:-.25pt'>PERMITTED BY LAW, THE SERVICE AND VENDOR SERVICES ARE PROVIDED “AS IS.” BeLocalFocused does not guarantee (a) the appearance and/or location of any listing or advertisement, (b) the level of results you will achieve from the Service or (c) that the Service will meet your requirements.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.6pt; margin-left:-.25pt'>The BeLocalFocused Terms of Service are incorporated by reference and made a part of these terms, including without limitation, all terms related to limitation of liability and indemnification, governing law and venue.</p>
    <h3 style='margin-left:-.25pt'>Premium Subscription Services</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.05pt; margin-left:-.25pt'>We may offer from time-to-time additional, premium subscription services on BeLocalFocused for business owners and marketing organizations. These premium subscription services will be subject to additional terms, conditions, and limitations for the user for such services. You agree that you are bound by these additional terms when you sign up for these premium services. We provide links below to the terms that govern our current offerings of premium subscription services.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.65pt; margin-left:-.25pt'>We may bundle various products in different subscriptions. You can elect which bundled services you which to purchase when you place an order with us. Any monthly plans for premium subscription services are payable in advance, are not refundable, and may be canceled at any time by you.&nbsp; We may offer special prices for longer-term subscriptions that require longer-term commitments, such as three months, six months or a year. Such plans may not be canceled during the term and are non-refundable. All premium subscriptions renew automatically unless canceled by you before any renewal date. We may modify and change these offerings at any time.</p>
    <h3 style='margin-left:-.25pt'>Premium Business Listing Service – Description and Important Disclaimers</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.1pt; margin-left:-.25pt'>BeLocalFocused Premium Business Listing Service is an optional fee-based service provided by BeLocalFocused to move your company listing into a higher ranking in the BeLocalFocused company browse and search results list for a 30-day (“Monthly”), 3month (“Quarterly”), 6-month (“Bi-annually), or twelve-month (“Annually”) period. Each category and location combination enables the participant to feature one (1) company text links in category and location combinations. Your Premium Business Listing is billed at the time of submission.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.35pt; margin-left:-.25pt'>BeLocalFocused reserves the right to decide whether, where, and how a Premium Business Listing is listed.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.2pt; margin-left:-.25pt'>BeLocalFocused reserves the right to reject a Premium Business Listing submission.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:11.9pt; margin-left:-.25pt'>All fees paid for the Premium Business Listing Service are NON-REFUNDABLE.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.85pt; margin-left:-.25pt'>A credit card is required to set-up the Premium Business Listing for the Monthly or annual period. All Premium Business Listings must conform to the BeLocalFocused editorial guidelines and must be relevant topically to the category and location. All Premium Business Listings are subject to final approval by the BeLocalFocused editorial team, which in their sole discretion may reject a Premium Business Listing request for any reason.</p>
    <h3 style='margin-left:-.25pt'>Listing Manager Terms</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:0in; margin-left:-.25pt'>These additional terms and the <span style='color:#214752'>BeLocalFocused Terms of Service</span> govern your subscription and use of Listing Manager. By signing up for Listing Manager, you agree to these terms.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.7pt; margin-left:36.05pt;text-indent:-18.05pt;line-height:99%'><span style='font-size:10.0pt;line-height:99%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> We offer a subscription (fee-based service) for the use of Listing Manager on a one month (“Monthly”), three months (“Quarterly”)&nbsp; or twelve month (“Annual”) basis.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> The Listing Manager service and all related features of this service shall be effective on the date you receive email confirmation of your purchase and will continue for an initial period (“Initial Period”) of Monthly, Quarterly or Annual period from this date as selected by you in your order.&nbsp; The Initial Period shall be renewed automatically for the same length of term as the Initial Period (Monthly, Quarterly or Annual) each (“Renewal Period”) and the Monthly, Quarterly or Annual fee will be billed to your credit card at the start of a Renewal Period.&nbsp; You can terminate your subscription prior to any Renewal Period by going to your subscription dashboard online&nbsp;</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You may only purchase subscriptions on your own behalf or on behalf of your business.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You will pay all charges you incur in connection with Listing Manager in immediately available funds. You agree to provide a valid payment method for Listing Manager and you agree to keep this information up to date.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> Payments are due in advance of the Initial or Renewal Periods. These fees are not refundable.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You authorize and direct us to charge your designated payment method for your subscription or, if your designated payment method fails, to charge any other payment method you have on file with us.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You authorize and direct us to retain information about the payment method(s) associated with your account. If we do not receive payment from your designated payment method or any other payment method on file, you agree to pay all amounts due upon demand by us.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> We do not permit or accept content from you that (a) violate applicable laws or regulations, (b) violate the rights of others, including copyrights or trademarks of others, (c) are misleading or inaccurate, or (d) promote (i) counterfeit goods, (ii) dangerous products or services such as weapons or recreational drugs, (iii) products or services that enable dishonest or unlawful behavior, (iv) obscenity, (v) alcoholic beverages, (vi) gambling related products or services, (vii) certain health-related products and services regulated by law, (vii) certain tobacco and similar products (e.g., such as e-cigarettes) regulated by law, or (viii) other products or services we deem in our sole discretion as being inappropriate or offensive.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> All content and information submitted by you shall be subject to our character limits, quality standards, BeLocalFocused Terms of Services, and other applicable listing policies.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> We may reject or remove any such content, in whole or in part, in our sole discretion, or modified at any time to comply with our policies and these terms.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> We do not guarantee (a) the appearance and/or location of any listing, (b) the level of results you will achieve from Listing Manager or (c) Listing Manager will meet your requirements.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You grant us a non-exclusive, worldwide, paid-up, royalty-free, transferable (in the event of a sale or other change of control of BeLocalFocused’s business), perpetual, irrevocable right and license to use, copy, publish, distribute, syndicate, reformat and update (for example, to improve accuracy and/or standardize formats) any and all listing content and all trademarks and branding associated with your Listing Manager listings.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:36.05pt;text-indent:-18.05pt'><span style='font-size:10.0pt; line-height:102%;font-family:Wingdings'>§<span style='font:7.0pt "Times New Roman"'>&nbsp;</span></span> You represent and warrant that you have all rights to provide the content and trademarks you submit for your Listing Manager listings.</p>
    <h3 style='margin-left:-.25pt'>Advertising Content</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.1pt; margin-left:-.25pt'>You may not submit content, creatives or advertising materials that (a) violate applicable laws or regulations, (b) violate the rights of others, including copyrights or trademarks of others, (c) are misleading or inaccurate, (d) violate the BeLocalFocused Terms of Service, or (d) promote (i) counterfeit goods, (ii) dangerous products or services such as weapons or recreational drugs, (iii) products or services that enable dishonest or unlawful behavior, (iv) obscenity, (v) alcoholic beverages, (vi) gambling related products or services, (vii) certain health-related products and services regulated by law, (vii) certain tobacco and similar products (e.g., such as e-cigarettes) regulated by law, or (viii) other products or services we deem in our sole discretion as being inappropriate or offensive.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.1pt; margin-left:-.25pt'>All content and information submitted by you for the advertisements shall be subject to BeLocalFocused’s character limits, quality standards, BeLocalFocused Terms of Services, and other applicable listing policies.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.35pt; margin-left:-.25pt'>You grant us a non-exclusive, worldwide, paid-up, royalty-free, transferable (in the event of a sale or other change of control of BeLocalFocused’s business), perpetual, irrevocable right and license to use, copy, publish, distribute, syndicate, reformat and update (for example, to improve accuracy and/or standardize formats) any and all information, creatives, content and all trademarks and branding associated with your business for the Service.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.85pt; margin-left:-.25pt'>BeLocalFocused may reject or remove any such content, in whole or in part, in our sole discretion, or modified at any time to comply with our policies and these terms. You represent and warrant that all information and authorizations provided by you are complete, correct and current.</p>
    <h3 style='margin-left:-.25pt'>Cancellation Policy</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:0in; margin-left:-.25pt'>All BeLocalFocused subscriptions are established on automatic renewals. Customers will be charged for their subscription on their renewal date unless we are notified to cancel services 3 business days prior to the renewal date. After a subscription is cancelled, the service will remain active for the duration of the subscription period and then the company profile will revert to a free company profile.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.1pt; margin-left:-.25pt'>Due to the type of information and services being sold, we, unfortunately, cannot accept returns of articles, profiles, lists or reports once they have been delivered to you. We cannot and do not warrant that the information available through this service is accurate, complete or updated but rather is provided to the user ‘as is’.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.1pt; margin-left:-.25pt'>Please be sure to read all available information about a product and our terms of service before you place your order.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.85pt; margin-left:-.25pt'>Please note that we are available Monday through Friday from 9 am to 6 pm ET, excluding holidays.</p>
    <h3 style='margin-left:-.25pt'>Billing Problems and Disputes</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.85pt; margin-left:-.25pt'>You must notify us about any billing problems or discrepancies within 60 days after they first appear on the statement you receive from your bank. If you do not bring such problems or discrepancies to our attention within 60 days, you agree that you waive the right to dispute such problems or discrepancies.</p>
    <h3 style='margin-left:-.25pt'>Terms for Agencies, Agents and Representatives</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.1pt; margin-left:-.25pt'>If you establish a BeLocalFocused account or profile on behalf of a company, organization, entity or brand as a representative or agent (such as a marketing or advertising agency, the “Agency”): (a) the terms “you” and “your”, as used throughout the Agreement apply to both Agency and Agency’s client (the “Client”), as applicable and (b) Agency agrees to abide by all the terms of this Agreement and the following supplemental terms.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.1pt; margin-left:-.25pt'>You understand and agree that (a) Agency is acting as agent for a disclosed principal (i.e., the Client) and (b) Agency will act as agent for taking responsibility and making payment on all amounts due for purchases made from BeLocalFocused. Agency shall provide a payment method for purchases as described in this Agreement. Client and Agency shall be jointly and severally liable for the payment of sums due hereunder, but we agree to look initially to Agency for the payment of sums due hereunder. Nothing in this Agreement relating to the payment of transacted amounts by Agency shall be construed so as to relieve Client for breach of its obligations under this Agreement.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.35pt; margin-left:-.25pt'>Agency represents and warrants that Agency is the duly authorized agent of Client with full power to act on Client’s behalf with respect to this Agreement, and Agency has the power to enter into, deliver and perform this Agreement on behalf of Client and Agency. The individual(s) executing this Agreement on Agency’s behalf is/are authorized to execute and deliver this Agreement. Agency agrees that this Agreement is the legal, valid and binding obligation of Agency and/or Client, and shall be enforceable against Agency and/or Client in accordance with its terms.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.9pt; margin-left:-.25pt'>We may from time to time offer special promotions and promotional pricing for Agencies on behalf of their Clients. Such promotions will be subject to additional terms that supplement this Agreement that you agree is binding on Agency and Client (“Promotions”). We reserve the right to cancel Promotions early or to extend offers without notice.</p>
    <h3 style='margin-left:-.25pt'>Disclaimer of Warranties</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:0in; margin-left:-.25pt'>We provide BeLocalFocused “as is”, “with all faults” and “as available.” YOUR USE OF BELOCALFOCUSED IS AT YOUR OWN RISK. Our Contributors and we make no express warranties or guarantees about BeLocalFocused and its Content. TO THE EXTENT PERMITTED BY LAW, WE DISCLAIM IMPLIED WARRANTIES THAT BeLocalFocused AND ITS CONTENT ARE MERCHANTABLE, OF SATISFACTORY QUALITY, ACCURATE, FIT FOR A PARTICULAR PURPOSE OR NEED, TIMELY, RELIABLE OR NON-INFRINGING.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>WE DO NOT GUARANTEE THE RESULTS THAT YOU MAY OBTAIN FROM YOUR USE OF</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>BeLocalFocused. WE DO NOT GUARANTEE THAT BeLocalFocused WILL MEET YOUR</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>REQUIREMENTS. WE DO NOT GUARANTEE THAT YOU WILL BE ABLE TO ACCESS OR</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.65pt; margin-left:-.25pt'>USE BeLocalFocused AT TIMES OR LOCATIONS OF YOUR CHOOSING. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY OUR REPRESENTATIVES SHALL CREATE A WARRANTY.</p>
    <h3 style='margin-left:-.25pt'>Limitation of Liability</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>OUR PARENT, OUR CONTRIBUTORS, OUR DISTRIBUTORS AND WE SHALL NOT BE</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR EXEMPLARY</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>DAMAGES ARISING FROM YOUR USE OF BeLocalFocused. THESE EXCLUSIONS APPLY</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>TO ANY CLAIMS FOR LOST PROFITS, LOST DATA, LOSS OF GOODWILL, WORK</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, OR ANY OTHER COMMERCIAL</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>DAMAGES OR LOSSES, EVEN IF WE KNEW OR SHOULD HAVE KNOWN THE</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>POSSIBILITY OF SUCH DAMAGES. BECAUSE SOME STATES OR JURISDICTIONS DO NOT</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>ALLOW THE EXCLUSION OR THE LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.1pt; margin-left:-.25pt'>INCIDENTAL DAMAGES, IN SUCH STATES OR JURISDICTIONS, OUR AND OUR SUPPLIER’S LIABILITY IN SUCH STATE OR JURISDICTION SHALL BE LIMITED TO THE EXTENT PERMITTED BY LAW.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>YOU AGREE, AND YOU WILL REQUIRE THAT ANY THIRD PARTY WHO INDIRECTLY</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>USES THE CONTENT PROVIDED BY YOU (“THIRD PARTY USER”) TO AGREE, THAT IN</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>NO EVENT SHALL WE OR OUR CONTRIBUTORS BE LIABLE FOR THE RESULTS OF ANY</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>THIRD PARTY USER’S USE OR RELIANCE UPON BeLocalFocused, FOR ITS INABILITY OR</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>FAILURE TO CONDUCT ITS BUSINESS, OR FOR DIRECT, INDIRECT, INCIDENTAL,</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>SPECIAL, CONSEQUENTIAL OR EXEMPLARY OR PUNITIVE DAMAGES, INCLUDING,</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.4pt; margin-left:-.25pt'>WITHOUT LIMITATION, DAMAGES FOR LOST DATA OR LOST PROFITS, WHETHER IN TORT (INCLUDING NEGLIGENCE), CONTRACT, STRICT LIABILITY, UNDER STATUTE, IN EQUITY, AT LAW, OR OTHERWISE.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:.6pt; margin-left:-.25pt'>IN NO EVENT SHALL OUR OR OUR CONTRIBUTORS CUMULATIVE LIABILITY TO YOU</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.85pt; margin-left:-.25pt'>FOR ANY AND ALL CLAIMS RELATING TO THE USE OF THE BeLocalFocused SERVICES EXCEED THE TOTAL AMOUNT YOU PAID FOR THE PARTICULAR BeLocalFocused SERVICE WITHIN AN IMMEDIATE TWELVE-MONTH PERIOD.</p>
    <h3 style='margin-left:-.25pt'>Termination</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.9pt; margin-left:-.25pt'>We may cancel or suspend your access to BeLocalFocused at any time, without cause and/or without notice. Your right to use BeLocalFocused will end once your service is terminated, and any data you have stored on BeLocalFocused may be unavailable later. We may cooperate with legal authorities and/or third parties in the investigation of any suspected or alleged crime or civil wrongdoing.</p>
    <h3 style='margin-left:-.25pt'>Indemnification</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:-.25pt'>Upon a request by us, you agree to defend, indemnify, and hold harmless us and our employees, contractors, officers, and directors from all liabilities, claims, and expenses, including attorney’s fees that arise from your use or misuse of BeLocalFocused. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will cooperate with us in asserting any available defenses.</p>
    <h3 style='margin-left:-.25pt'>Electronic Contracting and Notices</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:12.15pt; margin-left:-.25pt'>You agree to transact with us electronically. You agree that these Terms of Service have the same effect as an agreement signed in writing. You also agree that we may send to you in electronic form any privacy or other notices, terms, disclosures, reports, documents, communications or other records regarding BeLocalFocused (collectively, “Notices”) or anything related to your use of BeLocalFocused. We can send you electronic Notices (1) to the email address that you provided to us during registration; (2) via text message if you elected to receive any mobile alerts, (3) by posting the Notice on BeLocalFocused’s web page, mobile pages or applications. The delivery of any Notice from us is effective when sent by us, regardless of whether you read the Notice when you receive it or whether you actually receive the delivery. You can withdraw your consent to receive Notices electronically by cancelling or discontinuing your use of the applicable service.</p>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.85pt; margin-left:-.25pt'>Our terms and other Notices are designed for access on most current Internet Web browsers and on the mobile devices in which we offer mobile applications and services. In order to transact with us electronically, you must have a device and an Internet browser capable of accessing and browsing the Internet. If you wish to print a copy of the Term of Services, your device must have access to a printer that can print web pages from the print function of your Internet browsers. Also keep in mind that the “print” features on many devices and browsers will enable you to save a copy of the terms as a “note” or “PDF” file on your device.</p>
    <h3 style='margin-left:-.25pt'>Assignment</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:17.85pt; margin-left:-.25pt'>We may assign this contract at any time without notice to you. You may not assign this contract to anyone else.</p>
    <h3 style='margin-left:-.25pt'>Entire Agreement</h3>
    <p class="MsoNormal" style='margin-top:0in;margin-right:.65pt;margin-bottom:4.05pt; margin-left:-.25pt'>This Agreement and any supplemental terms, policies, rules and guidelines posted on BeLocalFocused constitute the entire agreement between you and us and supersede all previous written or oral agreements. If any part of this Agreement is held invalid or unenforceable, that portion shall be construed in a manner consistent with applicable law to reflect, as nearly as possible, the original intentions of the parties, and the remaining portions shall remain in full force and effect.</p>
  </div>
<p style="bottom: 10px; right: 10px; position: absolute;"><a href="https://wordtohtml.net" target="_blank" style="font-size:11px; color: #d0d0d0">Converted to HTML with WordToHTML.net</a></p>
            </div>
            
        </div>
    </div>
</div>
<!-- About city estate end -->

<!-- Footer start -->
<?php include("footer.php");?>
<!-- Footer end -->

<!-- Full Page Search -->
<div id="full-page-search">
    <button type="button" class="close">×</button>
    <form action="index.html#">
        <input type="search" value="" placeholder="type keyword(s) here" />
        <button type="submit" class="btn btn-sm button-theme">Search</button>
    </form>
</div>

<script src="js/jquery-2.2.0.min.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script  src="js/bootstrap-submenu.js"></script>
<script  src="js/rangeslider.js"></script>
<script  src="js/jquery.mb.YTPlayer.js"></script>
<script  src="js/bootstrap-select.min.js"></script>
<script  src="js/jquery.easing.1.3.js"></script>
<script  src="js/jquery.scrollUp.js"></script>
<script  src="js/jquery.mCustomScrollbar.concat.min.js"></script>
<script  src="js/leaflet.js"></script>
<script  src="js/leaflet-providers.js"></script>
<script  src="js/leaflet.markercluster.js"></script>
<script  src="js/moment.min.js"></script>
<script  src="js/daterangepicker.min.js"></script>
<script  src="js/dropzone.js"></script>
<script  src="js/slick.min.js"></script>
<script  src="js/jquery.filterizr.js"></script>
<script  src="js/jquery.magnific-popup.min.js"></script>
<script  src="js/jquery.countdown.js"></script>
<script  src="js/maps.js"></script>
<script  src="js/app.js"></script>

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script  src="js/ie10-viewport-bug-workaround.js"></script>
<!-- Custom javascript -->
<script  src="js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>